/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.sinetskiy;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
public class App {
    public static void main(String... args) {

        var atm = new ATM();

        atm.cashIn(Map.of(Denomination._5000_, 2, Denomination._1000_,8, Denomination._100_, 5));

        try {
            var cash = atm.withdrawal(10150);
            System.out.println(cash.entrySet());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        atm.printAccount();
    }
}
