/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus.sinetskiy;

import java.util.Map;


/**
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 * <p>
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 */
public class App {
    public static void main(String... args) {

        var atm = new ATM();

        atm.cashIn(1, Map.of(Denomination.D_5000, 2, Denomination.D_1000,8, Denomination.D_100, 5));

        try {
            var cash = atm.withdrawal(1,10150);
            System.out.println(cash.entrySet());
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        atm.printAccount(1);
    }
}
